# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetAdoptionApplicationForm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'SDWebImage', '~> 4.0'
  pod 'RKDropdownAlert', '~> 0.3'

  target 'PetAdoptionApplicationFormTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
